# HeroSMP - Minecraft 1.12.2
motd=HeroSMP - Super Heroes
server-port=25565
server-ip=
online-mode=true
white-list=false
pvp=true
difficulty=normal
gamemode=0
force-gamemode=false
max-players=20
spawn-protection=16
view-distance=8
allow-flight=true
enable-command-block=true
enable-query=false
enable-rcon=false
level-name=world
level-type=DEFAULT
generate-structures=true
spawn-npcs=true
spawn-animals=true
spawn-monsters=true
hardcore=false
